version: '3.8'

services:
  notes-api:
    build: .
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
